export const NAV_BEHAVIOR = {
  SINGLE_LINE: 'SINGLE_LINE',
  MULTILINE_WITH_BR: 'MULTILINE_WITH_BR',
  MULTILINE: 'MULTILINE'
}

export const LEFT_EXTREME_EDGE_POINT = 167
export const PERFECT_DIAPASON_FOR_CHARS = 6
export const TEXT_NODE_TYPE = 3